# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: "Instalando Nuget"

- task: UseDotNet@2
  displayName: "Instalando .NetCore 3.1"
  inputs:
    packageType: 'sdk'
    version: '3.1'

- task: DotNetCoreCLI@2
  displayName: "Restaurando packages"
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "Publish local"
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false

- task: NuGetCommand@2
  displayName: "Publish servidor"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'aeee8f1e-1c13-44da-a529-14a5f7e9290b'


